//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enterprise_Front_End.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourcePaths {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourcePaths() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Enterprise_Front_End.Properties.ResourcePaths", typeof(ResourcePaths).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controllers.
        /// </summary>
        public static string FolderController {
            get {
                return ResourceManager.GetString("FolderController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Views/Layouts.
        /// </summary>
        public static string FolderLayout {
            get {
                return ResourceManager.GetString("FolderLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Models.
        /// </summary>
        public static string FolderModel {
            get {
                return ResourceManager.GetString("FolderModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Views.
        /// </summary>
        public static string FolderView {
            get {
                return ResourceManager.GetString("FolderView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /NCRDetailsFrame.
        /// </summary>
        public static string FrameNCRDetails {
            get {
                return ResourceManager.GetString("FrameNCRDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /NCRListFrame.
        /// </summary>
        public static string FrameNCRList {
            get {
                return ResourceManager.GetString("FrameNCRList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /NCRNav.
        /// </summary>
        public static string FrameNCRNav {
            get {
                return ResourceManager.GetString("FrameNCRNav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /NCRSearchbarFrame.
        /// </summary>
        public static string FrameNCRSearchbar {
            get {
                return ResourceManager.GetString("FrameNCRSearchbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /LayoutBase.xaml.
        /// </summary>
        public static string LayoutBase {
            get {
                return ResourceManager.GetString("LayoutBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /DashboardPage.xaml.
        /// </summary>
        public static string PageDash {
            get {
                return ResourceManager.GetString("PageDash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /DashboardPage.
        /// </summary>
        public static string PageDashboard {
            get {
                return ResourceManager.GetString("PageDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pack://application:,,,/Views/Pages/Login/Login.xaml.
        /// </summary>
        public static string PageLogin {
            get {
                return ResourceManager.GetString("PageLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /MainPage.xaml.
        /// </summary>
        public static string PageMain {
            get {
                return ResourceManager.GetString("PageMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pack://application:,,,/Views/Pages/Navigation/PageNav.xaml.
        /// </summary>
        public static string PageNav {
            get {
                return ResourceManager.GetString("PageNav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pack://application:,,,/Views/Pages/NCR/NCRPage.xaml.
        /// </summary>
        public static string PageNCR {
            get {
                return ResourceManager.GetString("PageNCR", resourceCulture);
            }
        }
    }
}
